Repository CruGlobal/mpdx-react, pull requests merged in 2024-05, with the labels that each got.

#937 MPDX-7891 - Allow contact search on Organization Accounts without organization selected
  pages/accountLists/[accountListId]/settings/organizations/accountLists.page.tsx
  pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/SearchOrganizationsAccountLists.graphql
  pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/resolvers.ts
  pages/api/graphql-rest.page.ts
  src/components/Settings/Organization/AccountLists/AccountLists.tsx
Labels: On Staging, Preview Environment

#936 MPDX-7893 - Allowing users to add offline organizations to their accounts
  src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.test.tsx
  src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.tsx
Labels: On Staging, Preview Environment

#934 [no-Jira] Fix MUI menu component error
  src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx
Labels: Preview Environment

#935 MPDX-7892 - Connect Services organization modals referring to incorrect organization
  src/components/Settings/integrations/Organization/OrganizationAccordion.test.tsx
  src/components/Settings/integrations/Organization/OrganizationAccordion.tsx
Labels: On Staging, Preview Environment

#929 [no-Jira] Display cached contact details data immediately
  src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsHeader.tsx
  src/components/Contacts/ContactDetails/ContactDetailsTab/ContactDetailsTab.tsx
  src/components/Contacts/ContactDetails/ContactDonationsTab/ContactDonationsTab.tsx
  src/components/Contacts/ContactDetails/ContactDonationsTab/DonationsGraph/DonationsGraph.tsx
  src/components/Contacts/ContactDetails/ContactTasksTab/ContactTasksTab.tsx
Labels: On Staging

#938 [no-Jira] Fix 0 rendered next to Add Google Account button
  src/components/Settings/integrations/Google/GoogleAccordion.tsx
Labels: On Staging

#926 [no-Jira] Run `yarn gql:w` alongside the Next.js dev server
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .husky/post-checkout
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.24.5-e4447a1e48-755383192f.zip
  .yarn/cache/cliui-npm-8.0.1-3b029092cf-79648b3b00.zip
  .yarn/cache/concurrently-npm-8.2.2-8ae42f052b-8ac774df06.zip
  .yarn/cache/date-fns-npm-2.30.0-895c790e0f-f7be015232.zip
  .yarn/cache/rxjs-npm-7.8.1-41c443a75b-de4b53db10.zip
  .yarn/cache/shell-quote-npm-1.8.1-fcccf06093-5f01201f4e.zip
  .yarn/cache/spawn-command-npm-0.0.2-014d4d5d9f-e35c5d2817.zip
  .yarn/cache/tree-kill-npm-1.2.2-3da0e5a759-49117f5f41.zip
  .yarn/cache/yargs-npm-17.7.2-80b62638e1-73b572e863.zip
  README.md
  codegen.yml
  deleteStaleFiles.mjs
  package.json
  yarn.lock
Labels: On Staging

#943 [MPDX-7894] Save all of the user's past account list ids in the DataDog session
  pages/logout.page.tsx
  src/components/DataDog/DataDog.test.tsx
  src/components/DataDog/DataDog.tsx
  src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.tsx
  src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx
  src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.tsx
  src/hooks/__tests__/useDataDog.test.ts
  src/hooks/useDataDog.ts
  src/lib/apollo/client.ts
  src/lib/dataDog.test.ts
  src/lib/dataDog.ts
Labels: On Staging

#944 [MPDX-7894] Add user's language preference to the DataDog session
  src/components/DataDog/DataDog.tsx
  src/lib/dataDog.test.ts
  src/lib/dataDog.ts
Labels: On Staging

#947 HelpScout - 1154070 - Limit contact merge
  src/components/Contacts/MassActions/Merge/MassActionsMergeModal.test.tsx
  src/components/Contacts/MassActions/Merge/MassActionsMergeModal.tsx
Labels: Preview Environment
