Repository CruGlobal/mpdx-react, pull requests merged in 2024-08, with the labels that each got.

#987 HelpScout 1199960 - Fixing intlFormat.ts error when currency is not defined
  src/lib/intlFormat.test.ts
  src/lib/intlFormat.ts
Labels: Preview Environment

#973 MPDX-7946 use contact mutation when adding email
  src/components/Tool/FixEmailAddresses/AddEmailAddress.graphql
  src/components/Tool/FixEmailAddresses/EmailValidationForm.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.graphql
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressesMocks.ts
Labels: Preview Environment

#981 MPDX-7418 - Fix Email Addresses - Confirm Button
  src/components/Tool/FixEmailAddresses/EmailValidationForm.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson/FixEmailAddressPerson.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson/FixEmailAddressPerson.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx
Labels: Waiting on another PR, Preview Environment

#990 HelpScout 1199118 Update cache after contact deletion to prevent refresh
  src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.test.tsx
  src/components/Contacts/ContactDetails/ContactDetailsHeader/ContactDetailsMoreActions/ContactDetailsMoreActions.tsx
Labels: Preview Environment

#946 [no-Jira] Move InfiniteList components outside of ContactRow
  src/components/Contacts/ContactRow/ContactRow.tsx
Labels: On Staging, Preview Environment

#983 MPDX-8024 - Fix Send Newsletter - Confirm All Button
  src/components/Tool/FixSendNewsletter/Contact.test.tsx
  src/components/Tool/FixSendNewsletter/Contact.tsx
  src/components/Tool/FixSendNewsletter/FixSendNewsletter.test.tsx
  src/components/Tool/FixSendNewsletter/FixSendNewsletter.tsx
  src/components/Tool/FixSendNewsletter/FixSendNewsletterMock.ts
  src/components/Tool/FixSendNewsletter/InvalidNewsletter.graphql
Labels: Preview Environment

#982 MPDX-7416 - Fix Email Addresses - Confirm All Button
  src/components/Tool/FixEmailAddresses/EmailValidationForm.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson/FixEmailAddressPerson.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressPerson/FixEmailAddressPerson.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.graphql
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddressesMocks.ts
  src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx
Labels: Preview Environment

#997 MPDX-8054 Add google auth warning message
  src/components/Settings/integrations/Google/GoogleAccordion.test.tsx
  src/components/Settings/integrations/Google/GoogleAccordion.tsx
Labels: Preview Environment

#998 [no-Jira] Reapply the autocomplete focus patch to @mui/base
  .pnp.cjs
  .yarn/cache/@mui-base-patch-0c5c9c5ed4-728d6e97c6.zip
  .yarn/cache/@mui-base-patch-6da654589f-4a14fd43a4.zip
  .yarn/patches/@mui-base-npm-5.0.0-beta.40-248417914d.patch
  package.json
  yarn.lock
Labels: Preview Environment

#1000 [no-Jira] Remove duplicate GraphQL operation
  src/components/Tool/FixMailingAddresses/FixMailingAddresses.tsx
  src/components/Tool/FixMailingAddresses/GetInvalidAddresses.graphql
Labels: Preview Environment

#988 MPDX-7420 - Fix Email Addresses - add pagination
  pages/accountLists/[accountListId]/tools/fixEmailAddresses/[[...contactId]].page.test.tsx
  src/components/InfiniteList/InfiniteList.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.graphql
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.test.tsx
  src/components/Tool/FixEmailAddresses/FixEmailAddresses.tsx
  src/lib/apollo/cache.ts
Labels: Preview Environment

#1001 [MPDX-8061] Google Import
  pages/accountLists/[accountListId]/tools/import/csv.page.test.tsx
  pages/accountLists/[accountListId]/tools/import/csv.page.tsx
  pages/accountLists/[accountListId]/tools/import/google.page.test.tsx
  pages/accountLists/[accountListId]/tools/import/google.page.tsx
  pages/accountLists/[accountListId]/tools/import/tnt.page.tsx
  pages/api/Schema/Settings/Integrations/Google/googleAccounts/datahandler.ts
  pages/api/Schema/Settings/Integrations/Google/googleAccounts/googleAccounts.graphql
  pages/api/graphql-rest.page.ts
  src/components/Settings/integrations/Google/Modals/DeleteGoogleAccountModal.tsx
  src/components/Tool/GoogleImport/GoogleImport.test.tsx
  src/components/Tool/GoogleImport/GoogleImport.tsx
  src/components/Tool/GoogleImport/GoogleImportMocks.ts
  src/components/Tool/GoogleImport/googleContactGroups.graphql
  src/components/Tool/Home/ToolList.ts
  src/components/Tool/NoData.tsx
Labels: Preview Environment

#887 MPDX-7829 Ministries Have Self Service MPDX Donor/Account Removal Capability
  pages/accountLists/[accountListId]/settings/organizations/OrganizationsContext.tsx
  pages/accountLists/[accountListId]/settings/organizations/accountLists.page.tsx
  pages/accountLists/[accountListId]/settings/organizations/contacts.page.tsx
  pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/SearchOrganizationsAccountLists.graphql
  pages/api/Schema/Settings/Organizations/SearchOrganizationsAccountLists/datahandler.ts
  pages/api/Schema/Settings/Organizations/SearchOrganizationsContacts/SearchOrganizationsContacts.graphql
  pages/api/Schema/Settings/Organizations/SearchOrganizationsContacts/datahandler.ts
  pages/api/graphql-rest.page.ts
  src/components/InfiniteList/InfiniteList.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListCoachesOrUsers/AccountListCoachesOrUsers.test.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListCoachesOrUsers/AccountListCoachesOrUsers.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListInvites/AccountListInvites.test.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListInvites/AccountListInvites.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListRow.test.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/AccountListRow.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/DeleteAccountConfirmModal.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/DeleteAccountListsItems.graphql
  src/components/Settings/Organization/AccountLists/AccountListRow/DeleteUserConfirmModal.tsx
  src/components/Settings/Organization/AccountLists/AccountListRow/accountListRowHelper.ts
  src/components/Settings/Organization/AccountLists/AccountLists.graphql
  src/components/Settings/Organization/AccountLists/AccountLists.mock.ts
  src/components/Settings/Organization/AccountLists/AccountLists.test.tsx
  src/components/Settings/Organization/AccountLists/AccountLists.tsx
  src/components/Settings/Organization/Contacts/Contact.graphql
  src/components/Settings/Organization/Contacts/ContactRow/ContactRow.test.tsx
  src/components/Settings/Organization/Contacts/ContactRow/ContactRow.tsx
  src/components/Settings/Organization/Contacts/Contacts.test.tsx
  src/components/Settings/Organization/Contacts/Contacts.tsx
  src/components/Settings/Organization/Contacts/contactsMocks.ts
  src/components/Shared/Lists/listsHelper.ts
  src/components/common/Modal/ActionButtons/ActionButtons.tsx
  src/components/common/Modal/Confirmation/Confirmation.tsx
Labels: Preview Environment

#999 [MPDX-8075] Horizontally scroll flows view when dragging near the edges
  src/components/Contacts/ContactFlow/ContactFlow.tsx
  src/components/Contacts/ContactFlow/ContactFlowDragLayer/ContactFlowDragLayer.tsx
  src/components/Contacts/ContactFlow/ContactFlowDragLayer/useAutoScroll.test.ts
  src/components/Contacts/ContactFlow/ContactFlowDragLayer/useAutoScroll.ts
Labels: Preview Environment

#1003 [No-Jira] Change tools links
  pages/accountLists/[accountListId]/contacts/helpers.ts
  pages/accountLists/[accountListId]/tools/fix/commitmentInfo/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/fix/emailAddresses/[[...contactId]].page.test.tsx
  pages/accountLists/[accountListId]/tools/fix/emailAddresses/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/fix/mailingAddresses/[[...contactId]].page.test.tsx
  pages/accountLists/[accountListId]/tools/fix/mailingAddresses/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/fix/phoneNumbers/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/fix/sendNewsletter/[[...contactId]].page.test.tsx
  pages/accountLists/[accountListId]/tools/fix/sendNewsletter/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/merge/contacts/[[...contactId]].page.test.tsx
  pages/accountLists/[accountListId]/tools/merge/contacts/[[...contactId]].page.tsx
  pages/accountLists/[accountListId]/tools/merge/people/[[...contactId]].page.test.tsx
  pages/accountLists/[accountListId]/tools/merge/people/[[...contactId]].page.tsx
  src/components/Layouts/Primary/TopBar/Items/NavMenu/NavMenu.tsx
  src/components/Tool/Home/Home.tsx
  src/components/Tool/Home/Tool.test.tsx
  src/components/Tool/Home/Tool.tsx
  src/components/Tool/Home/ToolList.ts
  src/components/Tool/NavToolList/Item/Item.test.tsx
  src/components/Tool/NavToolList/Item/Item.tsx
  src/components/Tool/NavToolList/NavToolList.tsx
Labels: Preview Environment

#985 MPDX-7955 - List Header functionality
  src/components/Contacts/StarContactIconButton/StarContactIconButton.tsx
  src/components/Shared/Header/ListHeader.test.tsx
  src/components/Shared/Header/ListHeader.tsx
  src/components/Tool/Appeal/AppealDetails/AppealsMainPanel/AppealsMainPanelHeader.test.tsx
  src/components/Tool/Appeal/AppealDetails/AppealsMainPanel/AppealsMainPanelHeader.tsx
  src/components/Tool/Appeal/AppealsContext/AppealsContext.tsx
  src/components/Tool/Appeal/Flow/ContactFlowRow/ContactFlowRow.test.tsx
  src/components/Tool/Appeal/Flow/ContactFlowRow/ContactFlowRow.tsx
Labels: Preview Environment

#986 MPDX-7955 - Add edit appeal functionality
  src/components/Tool/Appeal/AppealDetails/AppealHeaderInfo.tsx
  src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/DynamicEditAppealHeaderInfoModal.tsx
  src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppeal.graphql
  src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppealHeaderInfoModal.test.tsx
  src/components/Tool/Appeal/AppealDetails/EditAppealHeaderInfoModal/EditAppealHeaderInfoModal.tsx
  src/components/Tool/Appeal/AppealsDetailsPage.test.tsx
  src/components/Tool/Appeal/List/ContactsList/ContactsList.tsx
Labels: Preview Environment

#1004 [MPDX-8088] Create setup start page
  README.md
  next.config.js
  pages/setup/start.page.test.tsx
  pages/setup/start.page.tsx
  src/components/Layouts/Primary/NavBar/NavTools/ProfileMenuPanel/ProfileMenuPanel.tsx
  src/components/Layouts/Primary/TopBar/Items/ProfileMenu/ProfileMenu.tsx
  src/components/Setup/SetupPage.tsx
  src/components/Setup/styledComponents.ts
  src/components/Shared/Links/Links.test.tsx
  src/components/Shared/Links/Links.tsx
  src/components/User/GetUser.graphql
Labels: Preview Environment

#1009 [MPDX-8089] Add setup connect page
  pages/setup/connect.page.test.tsx
  pages/setup/connect.page.tsx
  src/components/Settings/integrations/Organization/ConnectOrganization.test.tsx
  src/components/Settings/integrations/Organization/ConnectOrganization.tsx
  src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.test.tsx
  src/components/Settings/integrations/Organization/Modals/OrganizationAddAccountModal.tsx
  src/components/Settings/integrations/Organization/Modals/OrganizationEditAccountModal.tsx
  src/components/Settings/integrations/Organization/OrganizationAccordion.tsx
  src/components/Settings/integrations/Organization/schema.ts
  src/components/Setup/Connect.test.tsx
  src/components/Setup/Connect.tsx
  src/components/common/Modal/ActionButtons/ActionButtons.tsx
Labels: Preview Environment

#1021 [MPDX-8096] Add default account setup page
  pages/setup/Account.graphql
  pages/setup/account.page.test.tsx
  pages/setup/account.page.tsx
Labels: Preview Environment
