Repository CruGlobal/mpdx-react, pull requests merged in 2025-05, with the labels that each got.

#1303 [no-Jira] Upgrade clsx, formidable, and cross-spawn
  .pnp.cjs
  .yarn/cache/@noble-hashes-npm-1.8.0-a397449e64-06a0b52c81.zip
  .yarn/cache/@paralleldrive-cuid2-npm-2.2.2-e6061749b2-af5826df93.zip
  .yarn/cache/@types-formidable-npm-2.0.6-94d53f71b6-808a9bc112.zip
  .yarn/cache/@types-formidable-npm-3.4.5-1fa13c32d2-733dc59d4d.zip
  .yarn/cache/clsx-npm-2.1.0-29d286e1de-2e0ce7c3b6.zip
  .yarn/cache/clsx-npm-2.1.1-96125b98be-c4c8eb865f.zip
  .yarn/cache/cross-spawn-npm-7.0.3-e4ff3e65b3-e1a13869d2.zip
  .yarn/cache/cross-spawn-npm-7.0.6-264bddf921-053ea8b213.zip
  .yarn/cache/formidable-npm-2.1.2-40ba18d67f-d385180e04.zip
  .yarn/cache/formidable-npm-3.5.4-a3473998f7-3a311ce576.zip
  .yarn/cache/hexoid-npm-1.0.0-2274609209-f2271b8b6b.zip
  .yarn/cache/qs-npm-6.11.2-b118bc1c6f-f2321d0796.zip
  package.json
  pages/api/csv-update.page.ts
  pages/api/uploads/csv-upload.page.ts
  pages/api/uploads/upload-person-avatar.page.ts
  yarn.lock
Labels: Preview Environment

#1304 No-Jira Check to ensure pledgeAmount is not an empty string
  src/components/Contacts/ContactDetails/ContactDonationsTab/PartnershipInfo/EditPartnershipInfoModal/EditPartnershipInfoModal.tsx
Labels: On Staging

#1308 MPDX-8450 Read contact detail person from URL
  pages/accountLists/[accountListId]/contacts/ContactsWrapper.test.tsx
  pages/accountLists/[accountListId]/contacts/ContactsWrapper.tsx
  src/components/Contacts/ContactDetails/ContactDetailContext.tsx
  src/components/Contacts/ContactDetails/ContactDetails.test.tsx
  src/components/Contacts/ContactDetails/ContactDetailsTab/People/ContactDetailsTabPeople.tsx
Labels: Preview Environment

#1316 [MPDX-8569] Dashed donations goal line
  src/components/Dashboard/DonationHistories/DonationHistories.tsx
Labels: Preview Environment

#1317 [MPDX-8568] Improve Health Indicator missing data message
  src/components/Reports/HealthIndicatorReport/HealthIndicatorReport.tsx
Labels: Preview Environment

#1318 MPDX-8441 Contact Flows not updating
  src/components/Contacts/ContactFlow/ContactFlow.tsx
Labels: Preview Environment

#1312 MPDX-8374 - Helpducks filtering
  README.md
  next.config.ts
  pages/_document.page.tsx
  pages/api/helpjuice/[...path].page.ts
  pages/api/helpjuice/[...path].test.ts
  pages/api/helpjuice/api/questions/popular.page.ts
  pages/api/helpjuice/api/questions/popular.test.ts
  pages/api/helpjuice/search.page.ts
  pages/api/helpjuice/search.test.ts
Labels: On Staging, Preview Environment

#1320 [MPDX-8582] Adjust calculations when indicators are absent
  src/components/Reports/HealthIndicatorReport/HealthIndicatorFormula/HealthIndicatorFormula.tsx
  src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.test.tsx
  src/components/Reports/HealthIndicatorReport/HealthIndicatorGraph/useGraphData.ts
Labels: Preview Environment
